### ISSUE TITLE
Create a dynamic menu-driven program of searching algorithms along with their respective execution time in Java.

### ISSUE THREAD

**Issue by extracoolkid** [extracoolkid/Java_Programs_0_to_100#2]
1. Make a folder with the name of problem.
2. Add the code file along with a text file storing a brief description of problem.
3. Code should be with clear variable names.
4. Proper comments are mandatory.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @extracoolkid , please assign it to me.
